[package]
name = "cv-camera-placement"
version = "0.1.0"
edition = "2024"

description = "I honestly don't know help me please i can't code"
license = "MIT"

authors = ["Gloria Jin <gjin7909@gmail.com>"]

[dependencies]
gl = "0.17.0"
glutin = "0.24.0"

[build-dependencies]